### ISSUE TITLE
Command property in custom MarkupControl not working when Repeater

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#238]
For example 

SampleControl.dotcontrol
```
<dot:Button Text="Test" Click="{controlCommand: _control.DoAction}"></dot:Button>
```

SampleControl.cs
```
        public Command DoAction
        {
            get { return (Command)GetValue(DoActionProperty); }
            set { SetValue(DoActionProperty, value); }
        }
        public static readonly DotvvmProperty DoActionProperty
            = DotvvmProperty.Register<Command, SampleControl>(c => c.DoAction, null);
```

TestViewModel.cs
```
        public string Title { get; set; }
      public List<string> TestCollecion { get; set; } = new List<string>()

        public TestViewModel()
        {
            Title = "Hello from DotVVM!";
        }

        public void Action1()
        {
            Title = "Action1";
        }

        public void Action2()
        {
            Title = "Action2";
        }
```

And finnaly TestViewModel.dothtml
```
 <cc:SampleControl DoAction="{command: Action1()}"></cc:SampleControl> 
  <cc:SampleControl DoAction="{command: Action2()}"> </cc:SampleControl>
```

In normal page command works but in bs:Panel control
```
    <dot:Repeater DataSource="{value: TestCollecion}">
      <ItemTemplate>
      </ItemTemplate>
      <EmptyDataTemplate>
        <cc:DeleteButton OnClick="{command: Action1()}">
          <cc:DeleteButton OnClick="{command: Action2()}">
      </EmptyDataTemplate>
    </dot:Repeater>

```
click on Action2 throw System.InvalidOperationException: Sequence contains more than one matching element

Btw if place component in ItemTemplate only Action1 is called. Action2 do nothing

Tested on last git version

**Comment by martinsura** [comment]
Btw got same exception if i use two empty control on page 

For example
```
 <cc:InputForm></cc:InputForm>
 <cc:InputForm></cc:InputForm>
```

**Comment by martinsura** [comment]
After some deep investigation , there is problem in controlId generation:
```
onclick="dotvvm.postbackScript("_control.Click")('root', this, [], 'c68_c20', false, null, null ...
```

When I manulay deleted 'c68_c20' command works...

**Comment by exyi** [comment]
Thank you for your easy to replicate report. I think, I have fixed it (e99b3ba98b9d5a1a90f489f0521a5b7f4ef13b2e), could you please try it on newest version from master? I was testing it on the new sample and it seem to work.

**Comment by martinsura** [comment]
Still not working. Getting exception

```
System.Linq.Enumerable.SingleOrDefault<TSource>(IEnumerable`1 source, Func`2 predicate) 
DotVVM.Framework.Controls.DotvvmControl.FindControlByUniqueId(String controlUniqueId) C:\Develop\Projects\dotvvm\src\DotVVM.Framework\Controls\DotvvmControl.cs +302
 302:                 result = result.GetAllDescendants(c => !IsNamingContainer(c))
```

Now getting exception after SelectItem in Select2 component changed...

**Comment by exyi** [comment]
@martinsura That's bad, I don't know how to replicate it now :(. Could you please break the sample here? I'll try to look at it tomorrow.

**Comment by martinsura** [comment]
@exyi Send you private message on gitter. Not sure if this same bug...

**Comment by exyi** [comment]
Solved by eb4208b11beefdb945b317638f170dc8bb39cc2e. There was a problem with unique id collision.
