### ISSUE TITLE
Checkbox CheckedItems collection not populating in dotcontrol

### ISSUE THREAD

**Issue by nflawson** [riganti/dotvvm#642]
I have a Markup control that I am using in a popup BS Modal that uses a set of check boxes to set a packed string value in my View Model. Basically it is used to choose from a set of Security Roles so the resulting string should look like "Admin,User,Registered" etc.

Inside the dotcontrol I have...

`@viewModel System.Object, mscorlib
@baseType KmartForYou.Controls.PageRole, KmartForYou

<dot:CheckBox Text="Admin" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="Admin" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="HR Admin" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="HR Admin" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="Registered" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="Registered" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="User" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="User" Changed="{controlCommand: UpdateRole()}" />`

The Code Behind looks like...

`	public class PageRole : DotvvmMarkupControl
	{
		public PageRole()
		{
			UpdateRole();
		}

		public List<string> Roles {
			get { return (List<string>)GetValue(RolesProperty); }
			set { SetValue(RolesProperty, value); }
		}
		public static readonly DotvvmProperty RolesProperty
				= DotvvmProperty.Register<List<string>, PageRole>(c => c.Roles, new List<string>());

		public List<string> PageRoles {
			get { return (List<string>)GetValue(PageRolesProperty); }
			set { SetValue(PageRolesProperty, value); }
		}
		public static DotvvmProperty PageRolesProperty
				= DotvvmProperty.Register<List<string>, PageRole>(c => c.PageRoles, new List<string>() { "Admin", "HR Admin" });

		public string Selected {
			get { return (string)GetValue(SelectedProperty); }
			set {
				SetValue(SelectedProperty, value);
			}
		}
		public static readonly DotvvmProperty SelectedProperty
				= DotvvmProperty.Register<string, PageRole>(c => c.Selected, "");

		public void UpdateRole()
		{
			Selected = string.Join(",", PageRoles.Select(i => i.ToString()));
		}
	}
`
Pretty much a classic version of the sample except the PageRoles property is now a Dotvvm Property and not a C# Property as in the sample. 

If I use the above code directly in my page and make the PageRoles a pure C# property, as in the sample, everything works perfectly.

When I use the above code in my control, Dotvvm correctly checks the checkboxes forthe initial values in my control; so Dotvvm is seeing the PageRoles property as a valid source collection for CheckedItems.

When I try clicking any checkbox the command is triggered but the collection hasn't changed and I get this **'Attempted to write to readonly property 'PageRoles' at 'function(){return {"Selected":PageRole,"PageRoles":["Admin","HR Admin"],"Roles":$control.Roles} }**' in the browser console. So the error appears to be happening in the JS.

I initially tried removing the Readonly attribute of the PageRolesProperty Dotvvm property but this made no difference and I still get the same message. 

I also tried making PageRoles just a C# property (without the PageRolesProperty Dotvvm Property) and under these circumstances the initial values remain unchecked so Dotvvm doesn't see it as a valid source collection and it doesn't update the collection if I change the values.

Any thoughts?

**Comment by adamjez** [comment]
Hi, it looks its the same issue like in https://github.com/riganti/dotvvm/issues/639 . It should be fixed in next dotvvm release.



________________________________
Od: Neil Lawson <notifications@github.com>
Odesláno: Tuesday, September 11, 2018 10:25:23 AM
Komu: riganti/dotvvm
Kopie: Subscribed
Předmět: [riganti/dotvvm] Checkbox CheckedItems collection not populating in dotcontrol (#642)


I have a Markup control that I am using in a popup BS Modal that uses a set of check boxes to set a packed string value in my View Model. Basically it is used to choose from a set of Security Roles so the resulting string should look like "Admin,User,Registered" etc.

Inside the dotcontrol I have...

`@viewmodel<https://github.com/viewmodel> System.Object, mscorlib
@basetype<https://github.com/basetype> KmartForYou.Controls.PageRole, KmartForYou

<dot:CheckBox Text="Admin" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="Admin" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="HR Admin" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="HR Admin" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="Registered" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="Registered" Changed="{controlCommand: UpdateRole()}" />

<dot:CheckBox Text="User" CheckedItems="{value: _control.PageRoles}" Validation.Enabled="false" CheckedValue="User" Changed="{controlCommand: UpdateRole()}" />`

The Code Behind looks like...

` public class PageRole : DotvvmMarkupControl
{
public PageRole()
{
UpdateRole();
}

        public List<string> Roles {
                get { return (List<string>)GetValue(RolesProperty); }
                set { SetValue(RolesProperty, value); }
        }
        public static readonly DotvvmProperty RolesProperty
                        = DotvvmProperty.Register<List<string>, PageRole>(c => c.Roles, new List<string>());

        public List<string> PageRoles {
                get { return (List<string>)GetValue(PageRolesProperty); }
                set { SetValue(PageRolesProperty, value); }
        }
        public static DotvvmProperty PageRolesProperty
                        = DotvvmProperty.Register<List<string>, PageRole>(c => c.PageRoles, new List<string>() { "Admin", "HR Admin" });


        public string Selected {
                get { return (string)GetValue(SelectedProperty); }
                set {
                        SetValue(SelectedProperty, value);
                }
        }
        public static readonly DotvvmProperty SelectedProperty
                        = DotvvmProperty.Register<string, PageRole>(c => c.Selected, "");


        public void UpdateRole()
        {
                Selected = string.Join(",", PageRoles.Select(i => i.ToString()));
        }
}


`
Pretty much a classic version of the sample except the PageRoles property is now a Dotvvm Property and not a C# Property as in the sample.

If I use the above code directly in my page and make the PageRoles a pure C# property, as in the sample, everything works perfectly.

When I use the above code in my control, Dotvvm correctly checks the checkboxes forthe initial values in my control; so Dotvvm is seeing the PageRoles property as a valid source collection for CheckedItems.

When I try clicking any checkbox the command is triggered but the collection hasn't changed and I get this 'Attempted to write to readonly property 'PageRoles' at 'function(){return {"Selected":PageRole,"PageRoles":["Admin","HR Admin"],"Roles":$control.Roles} }' in the browser console. So the error appears to be happening in the JS.

I initially tried removing the Readonly attribute of the PageRolesProperty Dotvvm property but this made no difference and I still get the same message.

I also tried making PageRoles just a C# property (without the PageRolesProperty Dotvvm Property) and under these circumstances the initial values remain unchecked so Dotvvm doesn't see it as a valid source collection and it doesn't update the collection if I change the values.

Any thoughts?

**Comment by nflawson** [comment]
Is there a beta release with this fix in it that I can access?

**Comment by exyi** [comment]
@nflawson I'm not aware of that, you can wait for a release on public NuGet or simply grab the latest version from git. It should be pretty easy - you just clone the repository somewhere and then replace `<PackageReference Include="DotVVM.AspNetCore" ... />` with `<ProjectReference Include="path/to/dotvvm/src/DotVVM.Hosting.AspNetCore/DotVVM.Hosting.AspNetCore.csproj" />` (provided you don't use the obsolete project system).

**Comment by adamjez** [comment]
@nflawson we released new preview version **2.03-preview01-final**. Can you test if it resolves your issue?

**Comment by nflawson** [comment]
I don't get the error but it still doesn't work. My command gets called but the collection still isn't being updated. I tried converting the List<string> to string[] and I get the same result -the defaulted checkboxes are checked (so the array or list values are both being found and their values read). The problem continues to be around the system populating the CheckedItems list (array).

I've tried putting break points on the events (init, prerender etc) to see if the values are being set and then unset but the list contents doesn't change. I still suspect that the problem is with the JS (either Knockout or DotVVM).

My code uses a repeater and a dynamic list of potential values so my code looks like...

`<dot:Repeater DataSource="{value: _control.Roles}" WrapperTagName="ul" RenderWrapperTag="true">
	<li>
		<dot:CheckBox CheckedItems="{value: _control.PageRoles}" CheckedValue="{{value:  _this}}" Changed="{command: _control.UpdateRoles()}">
		{{value:  _this}}
		</dot:CheckBox>
	</li>
</dot:Repeater>`

The Server side looks like...

`			public List<string> Roles {
			get { return (List<string>)GetValue(RolesProperty); }
			set { SetValue(RolesProperty, value); }
		}
		public static readonly DotvvmProperty RolesProperty
				= DotvvmProperty.Register<List<string>, PageDetailForm>(c => c.Roles, new List<string>());

	public string PageRole {
			get { return (string)GetValue(PageRoleProperty); }
			set {
				SetValue(PageRoleProperty, value);
				PageRoles = value.Split(",");
			}
		}
		public static DotvvmProperty PageRoleProperty
				= DotvvmProperty.Register<string, PageDetailForm>(c => c.PageRole, "");

		public string[] PageRoles {
			get { return (string[])GetValue(PageRolesProperty); }
			set { SetValue(PageRolesProperty, value); }
		}
		public static readonly DotvvmProperty PageRolesProperty
				= DotvvmProperty.Register<string[], PageDetailForm>(c => c.PageRoles, new string[] { "Admin", "HR Admin" });


		public void UpdateRoles()
		{
			PageRole = string.Join(",", PageRoles);
		}
`


So, I'm sorry but either this wasn't the same as #639 or the fix hasn't worked.

**Comment by exyi** [comment]
Hi @nflawson, you can't update properties of controls when they are not bound to view model, it's the only state that is synchronized between the server and client. Setting properties in code-behind only works when it's assigned during the first request as it controls how is the HTML generated.
